version: "3"

tasks:
  run:
    cmds:
      - |
        echo "
        ███╗   ███╗ ██████╗  ████████╗  █████╗  ██╗      ██╗  ██╗
        ████╗ ████║ ██╔══██╗ ╚══██╔══╝ ██╔══██╗ ██║      ██║ ██╔╝
        ██╔████╔██║ ██████╔╝    ██║    ███████║ ██║      █████╔╝ 
        ██║╚██╔╝██║ ██╔══██╗    ██║    ██╔══██║ ██║      ██╔═██╗ 
        ██║ ╚═╝ ██║ ██║  ██║    ██║    ██║  ██║ ███████╗ ██║  ██╗
        ╚═╝     ╚═╝ ╚═╝  ╚═╝    ╚═╝    ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝
        "
      - task: up

  up:
    cmds:
      - docker-compose up -d
      - bun i
      - bun run dev
